### ISSUE TITLE
initiate github action for unit testing

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#100]
to enable fast feedback if unit test fail before merging to main branch

**Comment by victorskl** [comment]
Also to investigate GitHub <> CodeBuild integration. Fairly new, but it is valuable if this work well.

- https://aws.amazon.com/about-aws/whats-new/2023/07/aws-codebuild-github-actions/
- https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html
- https://www.google.com/search?q=codebuild+github+action
