### ISSUE TITLE
filemanager: implement a querying Lambda function

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#110]
In order to support #109, another Lambda function should be written which processes API gateway requests for querying the database. Some initial query parameters could be supported, e.g. `/objects?key=...&bucket=...`, or we could have some sort of filter query parameter, e.g. `/objects?filter=bucket:bucket-name`.

**Comment by mmalenic** [comment]
For the filter parameter, we could take inspiration from something like this: https://google.aip.dev/160.

**Comment by reisingerf** [comment]
Possible initial query use cases as discussed on [Slack](https://umccr.slack.com/archives/C03ABJTSN7J/p1708908553181809):

- find all FASTQs (by suffix for now)
- find all files given a `portal run id` (or more general a path fragment)

Perhaps even combine queries, e.g. 
- find VCF, TSV, JSON files for a given `portal run id`
- find FASTQs created within a given timeframe
- find FASTQs smaller than 10MB
- list FASTQs in archive
