### ISSUE TITLE
Implement ICAv2 workflow pipeline event notification

### ISSUE THREAD

**Issue by victorskl** [umccr/orcabus#120]
Actions:

- Create CDK stateful code construct for setting up pipeline analysis event notification
- Use "BSSH trial" <> "trial" in `umccr-prod` domain as the development target
- Document the event setup in this repo `/docs` section; similar expectation [like Portal ICAv1](https://github.com/umccr/data-portal-apis/tree/dev/docs/pipeline/ica_v1_event)

```
                                                                               / --> Step Function
ICAv2 --> SQS --> EventBridge Pipe --> EventBridge Bus --> EventBridge Rule --> ... 
                                                                               \ --> Some arbitrary execution (Container/Lambda/ECS/Batch)
```

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OrcaBus V1: Create and experiment ICA v2 Notification service subscription on Pipeline/Workflow run](https://trello.com/c/D9jpbK2S/1441-orcabus-v1-create-and-experiment-ica-v2-notification-service-subscription-on-pipeline-workflow-run)

**Comment by reisingerf** [comment]
Perhaps take a look at: https://github.com/EYssel/sqs-dlq-monitoring

**Comment by victorskl** [comment]
@reisingerf Flo has started the work item in the branch [feature/ica-event-pipe](https://github.com/umccr/orcabus/tree/feature/ica-event-pipe)

**Comment by victorskl** [comment]
Upstream related:
- https://github.com/EYssel/sqs-dlq-monitoring/issues/89
- https://github.com/EYssel/sqs-dlq-monitoring/issues/90

**Comment by EYssel** [comment]
Hi,

EYssel here, creator of [sqs-dlq-monitoring](https://github.com/EYssel/sqs-dlq-monitoring.)

I attempted to solve the issues mentioned. Feel free to let me know if you have any issues.

Thanks again for the great feedback!

**Comment by reisingerf** [comment]
@EYssel thanks for your construct! It made this work so much easier!
And your quick and helpful support was much appreciated!
