### ISSUE TITLE
db secret rotation

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#127]
secret rotation should be implemented at:

- db superuser secret defined [here](https://github.com/umccr/orcabus/blob/19b9bf194dc97c7171ea46f2edafac3ea09bdbe8/lib/workload/stateful/database/component.ts#L101)
	which then could remove the cdk-nag supression defined in the test [here](https://github.com/umccr/orcabus/blob/19b9bf194dc97c7171ea46f2edafac3ea09bdbe8/test/stateful/stateful-deployment.test.ts#L29-L35)
- microservice db role created by `orcabus-create-pg-login-role` (the secret manager here is out of IaC stack) #126

**Comment by victorskl** [comment]
Ref:
- https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotate-secrets_turn-on-for-db.html
- https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html

**Comment by victorskl** [comment]
It might just be straight forward...
- https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager-readme.html#rotating-database-credentials
