### ISSUE TITLE
initiate metadata-manager deployment

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#129]
- deploy metadata-manager using existing shared resources
- integrate the deployment stack with the existing codepipeline

**Comment by victorskl** [comment]
Hear you; the concern raised in [this Slack thread](https://umccr.slack.com/archives/C03ABJTSN7J/p1710217170423539), Will.

Please hold on this work item for a moment.
We shall make one more final round check and balance with tech choice decision making.

Sorry to delay you down a bit here. This is on me.
