### ISSUE TITLE
filemanager: consider using cargo-lambda-cdk instead of aws-cdk-lambda

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#133]
[This](https://github.com/cargo-lambda/cargo-lambda-cdk/tree/main) project is more up to date and maintained than the current [aws-cdk-lambda](https://github.com/rnag/rust.aws-cdk-lambda/tree/main) that filemanager uses. It also seems to have slightly simpler configuration, so we should investigate whether it's worthwhile to switch.

**Comment by mmalenic** [comment]
[cargo-lambda-cdk](https://github.com/cargo-lambda/cargo-lambda-cdk/tree/main) also supports bundling the Lambda code using docker, which is convenient for CodeBuild because there is no requirement to install Rust or `cargo lambda`.

**Comment by mmalenic** [comment]
@brainstorm might be able to remove those `query_*` files by using the before command hook to run the local database when building with cargo-lambda-cdk: https://github.com/cargo-lambda/cargo-lambda-cdk?tab=readme-ov-file#command-hooks

**Comment by brainstorm** [comment]
> @brainstorm might be able to remove those `query_*` files by using the before command hook to run the local database when building with cargo-lambda-cdk: https://github.com/cargo-lambda/cargo-lambda-cdk?tab=readme-ov-file#command-hooks

Ohhh, yesyesyes!
