### ISSUE TITLE
Proper GraphQL API support for metadata manager

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#137]
EdgeDb have an inbuilt `/graphql` endpoint but we wanted to have GraphQL for read-only. The current graphql is proxied to the metadata_manager app and reject request that contain `mutation` keyword. This could potentially led issue to query schema or do other stuff. Perhaps exploring read-only user access for EdgeDb could be a better way to deal with.

Ref: https://www.edgedb.com/docs/datamodel/access_policies

**Comment by williamputraintan** [comment]
👋 - Moving away from EdgeDb

**Comment by victorskl** [comment]
😿 GraphQL, one day in future down the track.! Not giving up yet.
