### ISSUE TITLE
Implement Copy Fastq Outputs from BSSH Project Manager

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#147]
## Summary

The bssh manager runs performs the following logic:

Reads the bssh_output.json file from the BCLConvert run output folder

Collects the basespace run id from the bssh output json

Collects the run id from the run info xml

Collects the fastq list csv file from the BCLConvert run output folder

Read and return the fastq list rows as a list of dictionaries (gzip compressed / b64 encoded)

Collects the samplesheet path from the BCLConvert run output folder (as we might need this to go into the cttso directories)

Read and return the samplesheet as a dictionary (via the v2-samplesheet-maker package) (gzip compressed / b64 encoded)

Return a manifest of icav2 uris where each key represents a ICAv2 data uri (file) and the value is a list of icav2 uris where each uri is a destination for a given file.

## Flow Diagram

![image](https://github.com/umccr/orcabus/assets/8197659/983c752b-b621-40b8-a270-72ff2ecbf2b5)

**Comment by victorskl** [comment]
Service namespace: `orcabus.fqcp`
