### ISSUE TITLE
Implement Runtime Lambda Layer building as CDK synth

### ISSUE THREAD

**Issue by victorskl** [umccr/orcabus#16]
**Context:**

* About the task - how we build Python runtime dependencies as Lambda layer
* Currently we only consider Python as runtime. 
  * Hence, assuming dependency package building is still "light weight". 
  * Therefore, wiring this step as `cdk synth` process.

**Guide:**

* We have already used `bash` script and `Makefile` for this step as manual invocation. Please observe & study this arrangement.
  * `make build`
  * [Makefile](https://github.com/umccr/orcabus/blob/3cae7ada7a3d2f0c7907df2dadbd7894c809b59d/Makefile#L12)
  * Layers [component.ts](https://github.com/umccr/orcabus/blob/3cae7ada7a3d2f0c7907df2dadbd7894c809b59d/lib/workload/stateless/layers/component.ts)
  * Layers building script [create_layer_package.sh](https://github.com/umccr/orcabus/blob/3cae7ada7a3d2f0c7907df2dadbd7894c809b59d/lib/workload/stateless/layers/create_layer_package.sh)
* Likewise in bash script, where we assume/use `docker` CLI command to build the dependency packaging, consider using Docker Engine API to natively build within CDK TypeScript construct. Some pointers as follows.
  * https://docs.docker.com/engine/api/
  * https://www.npmjs.com/package/node-docker-api
  * https://github.com/umccr/infrastructure/blob/2a1d47c485d11f8a4a9bf0d2cd865f8450164876/cdk/apps/htsget/htsget/goserver.py#L370-L407

**Actions:**

* Create a new feature branch out from `refactor-setup` i.e. pending PR #13 
* Consider `refactor-setup` as future `main`
* Identify and use appropriate well maintained Docker SDK for TypeScript
* Refer TODO task that denote comment in `layers/components.ts` - `// TODO using docker SDK ...`

**Comment by andrewpatto** [comment]
What is the advantage to lambda layering here? Is the expectation that there are going to be _lots_ (10? 50?) python lambdas and they are all going to have exactly the same dependencies?

**Comment by victorskl** [comment]
Yes. There are going to be few 10s/20s dependencies. Most runtime implementations will be shared the same layer. Some won't. So, there will be multiple Lambda layers -- base/common, schema builder, etc...

**Comment by andrewpatto** [comment]
I'm just wondering why we don't let the CDK just build each lambda individually? What is the particular advantage in this case that we are gaining by the use of layers?
(lambda size? lambda speed?)

**Comment by victorskl** [comment]
> why we don't let the CDK just build each lambda individually?

Sound like, it could be that I might still miss something CDK capability. Dev-ing AWS natively is still new to me. 

May be, we chat more in next devops call. I will explain situation/usecase, better.

**Comment by victorskl** [comment]
This is now Trello-ed -- https://trello.com/c/vc3916yg/1423-orcabus-v1-implement-runtime-lambda-layer-building-as-cdk-synth

And, will be continue tracked there.

Part of Trello migration.

**Comment by victorskl** [comment]
Use CDK L2/L3 Construct. Else Docker/containered Lambda runtime.

Closing.
