### ISSUE TITLE
Create universal event archive for OrcaBus events

### ISSUE THREAD

**Issue by reisingerf** [umccr/orcabus#185]
We want to have a history / record of any and all events that go over the OrcaBus event bus. 
That's to replay events if need be, but also so we can check if any events have been missed and not been picked up by any event rules. 

EventBridge does support a bus archive, but we don't have control over it and can't inspect it. In order to get that level of access, we need to roll our own.

Basically: 
Add an EventRule to match any event that is going over the bus and write it as JSON to a dedicated S3 bucket using its timestamp (maybe structure by year/month prefixes).
S3 is not directly supported as event target, so that has to go via a facilitator like Lambda (or maybe StepFunctions).

**Comment by brainstorm** [comment]
> @brainstorm any suggestions or ideas regarding Athena at this point? The idea here is that those events could be loaded and queried by Athena at some point. We'd have different event types, each with its own payload (schema). Should we try to separate / annotate the event type or let any crawler figure that out while loading the data? I.e. a data partitioning by time only or by time and event type? The latter should be known, but it's not necessarily a given and determining the type is additional overhead.

In my experience, partitioning by year/month/day is usually enough (performance-wise) and also doesn't complicate things at the query level.

Also yes please 1000% to having types properly set since it helps a lot when loading it in i.e polars dataframes, otherwise we'd always have to have a preprocessing step on the notebooks/queries to transform columns to the proper types such as datetime et al.

**Comment by reisingerf** [comment]
OK, so a year/month/day partitioning and individual event JSON files simply with a timestamp name, regardless of event type.

**Comment by brainstorm** [comment]
> OK, so a year/month/day partitioning and individual event JSON files simply with a timestamp name, regardless of event type.

Ideally we'd need to calculate/project a bit the event volume(s) before deciding on that exact scheme though... i.e probably it's enough to partition via just year/month at our current usage volumes but becomes a problem when X dimension multipliers we want to query against come in?

**Comment by reisingerf** [comment]
Hm, hard to estimate atm
To start with it's going to be at the level of workflow, e.g. status updates and related events internally to orcabus, but yes the volume could increase quickly. 

I have no issues with a daily granularity. I don't think it has any significant downsides, right? 
It may also be better if we wanted to query around the change of month, e.g. easier to add one or two days before/after, rather than having to adding a full month. 
Also, when debugging we may want to limit the amount of data to process to one or few days.

**Comment by raylrui** [comment]
currently working on #226 , and Optional flag ```addCustomEventArchiver``` is added  in the event bus construct with params of vpc, SG, destination Bucket added if turn on custom archiver flag.

The output format will be:
S3 object of that event archived in dedicated s3 bucket.\
URI: s3://{bucket_name}/events/yaer={year}/month={month}/day={day}/{event_type}_{totalSeconds.microsecond}.json \
Example Outputs: ```s3://{bucket_name}/events/yaer=2024/month=04/day=16/WorkflowRequest_1713252338.243297.json```
