### ISSUE TITLE
test: avoid synthesizing the CDK stack in tests multiple times

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#190]
Ideally the cdk-nag tests should only have to synthesize the stack once, and base all assertions on the same stack after that. This would improve the speed at which the tests run, because it would avoid compiling code or bundling microservice assets multiple times.

**Comment by mmalenic** [comment]
Context, I think `Annotations.fromStack` synthesizes the stack everytime, and most tests use this method, for example:
https://github.com/umccr/orcabus/blob/9c8c806db5dbe7aa62965060d24420e8caeeb1fd/test/stateless/stateless-deployment.test.ts#L30-L33

In `aws-cdk-lib` this leads to: https://github.com/aws/aws-cdk/blob/69cff2eda84dacfe265d518fc88ccf55930f59c4/packages/aws-cdk-lib/assertions/lib/annotations.ts#L165

**Comment by williamputraintan** [comment]
Ahh just realise, perhaps #194 fixes this?

**Comment by mmalenic** [comment]
Yes, #194 fixed this.
