### ISSUE TITLE
Explore & Study Architecture

### ISSUE THREAD

**Issue by victorskl** [umccr/orcabus#2]
**Context:**

- This is high level epic card to track and explore OrcaBus architecture. Roughly around:
  - AWS EventBridge itself
  - Event Sourcing & CQRS
   - Choice of data store platform
  - Framework & tools
  
**Outcome:**

- [ ] OrcaBus architecture -- WIP `OrcaBus.drawio` in Google Drive
- [ ] Pilot case study -- using File indexing pipeline

**Comment by williamputraintan** [comment]
As a side note for AWS lambda and EventBridge integration. Possible to use built-in [lambda destination](https://aws.amazon.com/blogs/compute/introducing-aws-lambda-destinations/) to AWS EventBridge instead of calling from Boto3. Only works for lambda Async Invocation.

**Comment by victorskl** [comment]
Descoped/unlinked/untangled: _Pilot case study -- using File indexing pipeline_

---

This is now Trello-ed -- https://trello.com/c/KDVIxQfm/1407-orcabus-v1-orcabus-design-card

And, will be continue tracked there.

Part of Trello migration.

**Comment by victorskl** [comment]
At this point, we have few docs and doodles around. 

See Trello^^ and/or check it in #orcabus Slack.
ditto -- https://umccr.slack.com/archives/C03ABJTSN7J/p1708906477528089

Closing.
