### ISSUE TITLE
Remove / Deprecate BCLConvertWorkflowRequest.json in config/schema dir

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#225]

**Comment by victorskl** [comment]
@alexiswl Let me work on this. I have changes going around schema and, registry setup. So, I will sweep these now obsolete schemas along the way. Ok?

**Comment by victorskl** [comment]
Heads-up all Request schemas will be deprecated.

```
BclConvertWorkflowRequest.json
DragenWgsQcWorkflowRequest.json
WesLaunchRequest.json
WorkflowRequest.json
```
