### ISSUE TITLE
Prevent event duplication when archiving to bucket

### ISSUE THREAD

**Issue by reisingerf** [umccr/orcabus#244]
See:
s3://event-archive-bucket/events/year=2024/month=04/day=23/Event_from_aws_sqs_1713843860.201574.json
s3://event-archive-bucket/events/year=2024/month=04/day=23/Event_from_aws_sqs_1713843918.998975.json
s3://event-archive-bucket/events/year=2024/month=04/day=23/Event_from_aws_sqs_1713844049.748956.json

All have the same JSON payload including ICA `correlationId` and `timestamp`.
Probably due to the same event being handled multiple times. 

We need to investigate where that duplication happens, ICA side or EventBus, and how to best avoid it (or if need be collapse the events).

**Comment by raylrui** [comment]
From the events timestamp `1713843860.201574` `1713843918.998975` `1713844049.748956`, these events are different events, or at least trigger the lambda at different time, I will have a check of sqs - eventbus logic

**Comment by raylrui** [comment]
It may come from error in `logger.info` , please refer PR #247
