### ISSUE TITLE
Evaluate need for S3 access log retention in event-archive-bucket

### ISSUE THREAD

**Issue by reisingerf** [umccr/orcabus#245]
Do we need to retain access logs for this bucket? 
Could the same be achieved with CloudTrail S3 data events (which we do log on our Org level)?

**Comment by raylrui** [comment]
yes, sure @reisingerf I will remove he access logs from the bucket to CloudTrail

**Comment by raylrui** [comment]
Hi @reisingerf  As I check around for our could trail events, we may not need the to retain the server access logs for event archiver bucket, as the main purpose for this bucket is to "archive" already, and serve for event statistic and analysis. Pls Refer PR #247
