### ISSUE TITLE
Deprecate icav2-copy-batch-utility

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#293]
ICAv2 Copy Batch Utility as a stack is overkill.  

As @reisingerf suggested, each service that requires the copy batch utility can generate their own.  

Create a copy batch utility as a construct and then have microservices create their own versions of this construct.

**Comment by victorskl** [comment]
_(made me shock momentarily first)_

> Create a copy batch utility as a construct 

Composing it as a construct sound good.! 👍

**Comment by alexiswl** [comment]
It does mean that the cttsov2 service will have five step functions associated with its stack

**Comment by victorskl** [comment]
Hear you. Hang in there. Pls yell, if step functions started to become out of hand. We can always regroup and discuss on tech choices...

**Comment by brainstorm** [comment]
This decision makes sense, in whatever meeting that happened, I've been thinking the same while working on the ICAv1 copy batch utility stack, more generic constructs are needed and I reckon that AWS S3 Batch Ops can do a good job at that.

**Comment by alexiswl** [comment]
>  in whatever meeting that happened

No meeting, just orcabus daydreams in my head.  

One other benefits is that the step functions executions are less cluttered with different services. 
If I want to see when the cttso executed the copy batch I can easily find executions of this without needing to trawl through the bssh fastq copy executions (because they're different step functions now with different names).
