### ISSUE TITLE
Add PierianDx Pipeline Manager as a service

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#294]
The PierianDx Pipeline Manager will be in charge of collating icav2 outputs and uploading them to PierianDx.

We will then require case-generation, run-generation and informatics job generation steps in the launch step function.  

We should also implement a push service that can query statuses of running informatics jobs

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ctTSO500 V2 Migration: Confirm Pierian handles V2 inputs](https://trello.com/c/s95gUdtS/1622-cttso500-v2-migration-confirm-pierian-handles-v2-inputs)
