### ISSUE TITLE
analysisOutput JSON Str should just be key, value pairs in the 'data' key of the payload stack

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#302]

**Comment by victorskl** [comment]
This may as well be related to Stacky Glue refactor https://github.com/umccr/orcabus/pull/393

**Comment by alexiswl** [comment]
Sorry I don't even know what this is referring to.  

In future the analysisOutputUri will be part of the engineParameters object. engineParameters will be a key for the data object

**Comment by victorskl** [comment]
😭

**Comment by victorskl** [comment]
Put it something good to come with Glue refactor...

**Comment by alexiswl** [comment]
Closing, using 'inputs', 'engineParameters' and 'outputs' sections instead
