### ISSUE TITLE
Migrate 2.5.0 to 2.6.0 for ctDNA on ICAv2 

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#405]
cttsov2 release notes are here - [release notes](https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/trusight/oncology-500-ctdna/200057710_00_DRAGEN_TSO_500_ctDNA_v2_6_0_Analysis_Software_Customer_Release_Notes.pdf)

**Comment by alexiswl** [comment]
Bundle ID: b753fbd9-453b-428d-89bd-8596de7337de

Pipeline ID: c2dfdbaa-2074-44c7-8078-d33e13607061

**Comment by victorskl** [comment]
See also https://umccr.slack.com/archives/C025TLC7D/p1720668245378219
