### ISSUE TITLE
compress (and index) ctdna vcfs after ctdna success event

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#406]
ctdna vcfs should be compressed in order to be viewed in icav2

**Comment by victorskl** [comment]
See https://umccr.slack.com/archives/C025TLC7D/p1720687929530749

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ctTSO500 V2 Migration: Port V1 post-processing workflow](https://trello.com/c/7TXT9xJo/1624-cttso500-v2-migration-port-v1-post-processing-workflow)

**Comment by alexiswl** [comment]
Working with 2.6.0
