### ISSUE TITLE
Support V1 chemistry samples through cttso v2 pipeline

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#408]
Conclusion from discussion yesterday was that we ought to support v1 samples through the cttsov2 service.

**Comment by victorskl** [comment]
ditto - https://umccr.slack.com/archives/C06TL0CUMUG/p1721551495022079

**Comment by victorskl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ctTSO500 Accreditation: Move to workflow 1.2](https://trello.com/c/XWmgJRlv/1525-cttso500-accreditation-move-to-workflow-12)

**Comment by victorskl** [comment]
@ohofmann @mhlunimelb FYI - this will come with next OrcaBus release.
