### ISSUE TITLE
filemanager: add way to shorten attribute API querying

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#495]
As described in #462, ideally there would be a way to shorten querying top-level `attributes`:

E.g, instead of:
`/api/v1/s3_objects?attributes[portal_run_id]=...`

It could be:
`/api/v1/s3_objects?portal_run_id=...`

This is a bit of a challenge, as described in #492, because it involves capturing unknown parameters in the API.

This may not be the best idea, because it could lead to confusion and conflicts between the known parameters and unknown parameters. E.g. if the user typed `?object_id=...` it might be better to reject this request rather than assuming that this request was for the `attributes`. Note, that currently unknown parameters are not rejected with an error status code, which should probably be changed.

Some ideas on how to implement this:
* Allow any unknown parameters and assume that the user intends to query by `attributes`.
* Add a list of "allowed" parameters which can be used to query `attributes`. For example, just allowing `portal_run_id` and other important `attributes`. These could be configurable during deployment.

**Comment by reisingerf** [comment]
A shorter / dedicated way to query for attributes would be nice, yes.

I'd have thought something like this though:
```/api/v1/s3_objects/attribute?portal_run_id=...```

That should allow the differentiation between parameters of the `s3_object` itself and any additional parameters.

**Comment by mmalenic** [comment]
Nice, yeah, I think that's a good solution.
