### ISSUE TITLE
wgts qc kwik-glue sfn fails when no wgts qc samples are on the run

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#544]
We get a failure because no dynamodb attribute library_id_set has been set for this instrument run id.  

Can either place a 'choice' inside the trigger to determine if the item is present or initialise an empty set first

**Comment by victorskl** [comment]
Right. Guess these are for cases like BiModal assay only run, etc.

**Comment by alexiswl** [comment]
Yes, or cttso only, this doesn't cause any issues with glue processing just that a sfn errors out when it doesn't need to.  

At some point I'd like to put a slack webhook on all failed sfns in the orcabus so don't want these types of errors polluting the channel
