### ISSUE TITLE
Should tumor_normal output dir be tumor-normal?

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#559]
Noticed we've go a few different case types going on here:

```
aws s3 ls "s3://pipeline-prod-cache-503977275616-ap-southeast-2/byob-icav2/production/analysis/"
```

```
                           PRE bclconvert-interop-qc/
                           PRE cttsov2/
                           PRE tumor_normal/
                           PRE umccrise/
                           PRE wgtsQc/
```

Should `tumor_normal` instead be 'tumor-normal' and `wgtsQc` be `wgts-qc'?

**Comment by victorskl** [comment]
All in favour.

**Comment by victorskl** [comment]
While at it, would be great if you could harmonise `workflow_name` (equivalent of `type_name` from Portal Workflow table) there too. 

This is also related to object store output path^ prefix.

Something similar like [SecondaryAnalysisHelper](https://github.com/umccr/data-portal-apis/blob/dev/data_processors/pipeline/domain/workflow.py#L206) harmonisation or etc would be great.!

![image](https://github.com/user-attachments/assets/efc06cce-e94b-4514-9984-70b50b1e00c9)
