### ISSUE TITLE
Rearrange outputs for ORA-compression outputs

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#660]
Outputs for ORA compression for instrument runs should match their /primary/ counterparts.

Where the initial data is output as 
`/primary/<run_id>/<portal_run_id>`

ORA compression can be also structured as 

`/ora-compression/<run_id>/<portal_run_id>`

**Comment by victorskl** [comment]
Tagging in @reisingerf as he has some thought about archival arrangement...

**Comment by reisingerf** [comment]
Yes, we can use a dedicated prefix for the compression output (on the BYOB). 
(might indeed help setting specific version retention times / lifecycle rules)
Just to keep in mind: once moved to the archive, this will all end up simply arranged by date and portal_run_id.
