### ISSUE TITLE
filemanager: fix presigned URLs for objects under `pipeline-*-cache` buckets

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#669]
The filemanager API fails to create valid presigned URLs for objects under `pipeline-*-cache` buckets because the API function lacks permissions to access the bucket. This leads to a presigned URL that returns an `Access Denied` error.

**Comment by victorskl** [comment]
Related https://umccr.slack.com/archives/C03ABJTSN7J/p1731029630130289
