### ISSUE TITLE
Create lambda for running RNASums  

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#689]
Something for the new 'button' to trigger. 

~~Given a subject id, and a dataset, generate a ready event for RNASum using the latest version of UMCCRise and WTS for a given subject~~

Update: Given a portal run id (of an existing RNASum event), and a dataset id, find the READY event from the workflow manager and then perform a find-replace on all existing versions of that old portal run id with a new portal run id.  
For the new WorkflowRunStateChange READY event, remove the payload.refId attribute and refresh the 'timestamp' attribute with the current UTC time

**Comment by victorskl** [comment]
Related https://github.com/umccr/orca-ui/issues/74
