### ISSUE TITLE
sequence-run-manager: update SRM to handle BSSH events from ICAv2 ENS subscription

### ISSUE THREAD

**Issue by reisingerf** [umccr/orcabus#696]
Currently the SRM consumes events from BSSH in ICAv1. Since we switched to ICAv2 we no longer receive sequencing updates.

tasks:
- set up an ICAv2 ENS subscription for BSSH events
- create a EventBridge rule to consume the events
- process these new events, adapting to their new format (possibly requesting supporting information from the BSSH API)
- make the sequencing information available to be displayed via the OrcaUI

**Comment by reisingerf** [comment]
Example [event](s3://orcabus-universal-events-archive-472057503814/events/year=2024/month=11/day=14/Event_from_aws_sqs_1731545984.249164.json):

**Comment by raylrui** [comment]
event link for refer: https://ap-southeast-2.console.aws.amazon.com/s3/object/orcabus-universal-events-archive-472057503814?region=ap-southeast-2&bucketType=general&prefix=events/year%3D2024/month%3D11/day%3D14/Event_from_aws_sqs_1731545984.249164.json

**Comment by victorskl** [comment]
@raylrui Does this closed by #753?

**Comment by raylrui** [comment]
yes, @victorskl we can close this now
