### ISSUE TITLE
filemanager: API should allow singular and list-based queries for the same key

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#707]
The filemanager API can use `[]` to query for parameters that should be combined with an "or" condition. Query parameters without `[]` get combined into "and" conditions.

The following should be possible:

```
curl -H "Authorization: Bearer $TOKEN" https://file.dev.umccr.org/api/v1/s3?key=*.fastq.gz&key[]=*123*&key[]=*456*
```

Which could combine into a statement that looks like:

```sql
select *
from s3_object
where key like '%.fastq.gz' and (key like '%123%' or key like '%456%')
```

Currently this is not possible and results in a deserialization error:

```
"Failed to deserialize query string. Error: Multiple values for one key: \"key\""
```

Note, that I think the order of the query parameters shouldn't matter, so if they are out of order, keys with `[]` would be grouped anyway. Fixing this still won't enable complex logic that involves nesting conditions.

**Comment by williamputraintan** [comment]
Do you think it makes sense to put `or` or an `and` (e.g. `...&key[and]=*123*&key[and]=*.html` ) within the square bracket and support both operators for multi-keys search? Then you can't mix and match between and/or for multi-keys search.

I was doing a file filtering as below, intuitively it should mean search all HTML files in the `rnasum` folder but this would just show all files in `rnasum` folder and all `html` files. 

![Screenshot 2024-12-05 at 11 39 18](https://github.com/user-attachments/assets/ea4e8e3c-2be1-4cad-9550-d58f27a80f06)

**Comment by williamputraintan** [comment]
AWS lambda search doesn't seems to support mixing and/or operator

https://github.com/user-attachments/assets/9af3aa2a-9cf7-419a-bb5d-9d033d85838c

**Comment by mmalenic** [comment]
> Do you think it makes sense to put or or an and (e.g. ...&key[and]=*123*&key[and]=*.html ) within the square bracket and support both operators for multi-keys search?

Yeah could do something like this. Could potentially also allow mixing `and` and `or` by grouping together all the `and` parameters and all the `or` parameters. Not sure if that makes sense though.

> AWS lambda search doesn't seems to support mixing and/or operator

Do you think the filemanager API should support this anyway?

**Comment by williamputraintan** [comment]
> > Do you think it makes sense to put or or an and (e.g. ...&key[and]=_123_&key[and]=*.html ) within the square bracket and support both operators for multi-keys search?
> 
> Yeah could do something like this. Could potentially also allow mixing `and` and `or` by grouping together all the `and` parameters and all the `or` parameters. Not sure if that makes sense though.
> 
> > AWS lambda search doesn't seems to support mixing and/or operator
> 
> Do you think the filemanager API should support this anyway?

I don't think so. I am not sure about the use case yet or was there a use case for this kind of query?
