### ISSUE TITLE
Only ctDNA types should go through the cttsov2 pipeline

### ISSUE THREAD

**Issue by alexiswl** [umccr/orcabus#717]
ctTSOV2 and ctTSO are the chemistry types (ASSAY) but we may run WGS through this chemistry (for lols?), these should not go through the ctTSOV2 pipeline and should not go through PierianDx.

**Comment by mhlunimelb** [comment]
I think it was still undecided. From the lab perspective, I think it is considered the same library, and I don't think there was any ability planned for qlims to give it a second libID.
But I think we had requested that it has a different libID for our current system.
It really would be best if it had a second libID - or some kind of suffix on the libID or something to tell the pre-enriched lib (WGS) apart from the enriched lib, they would never be treated as the same lib for downstream analysis.

**Comment by mhlunimelb** [comment]
However we decide to deal with TYPE + ASSAY, ctDNA WGS really needs its own "associations" - so it is has different UMIs and adapters from the TRUSEQ nano WGS, (and maybe trim settings different for BCL conver too?), but it needs to be processed with WGS analysis pipelines, never with the ctTSO pipelines.

**Comment by mhlunimelb** [comment]
Maybe we should check with the lab if it would be possible to treat the ctDNA WGS lib as an externally supplied lib and give it its own PRJ sampleID / libID?

**Comment by ohofmann** [comment]
Strongly agree that it would need to be at least its own library ID.

**Comment by victorskl** [comment]
Related https://umccr.slack.com/archives/C016A5BSKRC/p1732146842417509
