### ISSUE TITLE
filemanager: link bucket EventBridge rules to an SQS queue

### ISSUE THREAD

**Issue by mmalenic** [umccr/orcabus#86]
An EventBridge rule should be setup on a bucket that passes events to an SQS queue that filemanager can use. This should be a separate component in the stateful directory. As part of this, a DLQ should be setup for events that cannot be processed, which triggers a CloudWatch alarm.

**Comment by victorskl** [comment]
Recap from the initial Slack [thread](https://umccr.slack.com/archives/C03ABJTSN7J/p1705642247415679)

(FM next story card)
- OA bucket event for FM
	- [x] EB on at bucket in dev account 
	- [ ] EB rule, SQS/DLQ & alarm (CDK stateful stack/construct e.g. call it `data_event` or name appropiately)
        ```
		EB Rule --> SQS --> Lambda
			     |
			    DLQ --> CW alarm
        ```
	- Then, SQS url is the only input config for FM app
		- can be static constant or SSM param

**Ref:**

Here are TF codebase for background with how current Portal does this.
As mentioned, this is just for reference pointer. Not to follow how it done the exact way i.e. event routing part. 

SNS topic, DLQ CW alarm, bucket name might be useful pointers.

* https://github.com/umccr/infrastructure/tree/master/terraform/stacks/umccr_data_portal/app
* https://github.com/umccr/infrastructure/tree/master/terraform/stacks/data_archive
