### ISSUE TITLE
new database per microservice

### ISSUE THREAD

**Issue by williamputraintan** [umccr/orcabus#99]
A mechanism to create database names for each microsrvice and remove passing master secret to stateless stack

Ref: https://github.com/umccr/orcabus/pull/92#discussion_r1479241166

**Comment by andrewpatto** [comment]
The "best" mechanism to truly restrict access is RDS IAM - but that isn't normal db connection strings. It has to be enabled in the database etc and the connection strings are like v4 pre-signed strings.
So if you have a lot of control over your clients then that is the best - and then in that case the IAM permissions for the microservice can have conditionals etc down to the database (not just instance) level.

Is hard to wedge it in where you don't have control over the client lifecycle (Edgedb for instance? Though that has enough hooks that it might work)

**Comment by andrewpatto** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html

**Comment by andrewpatto** [comment]
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "rds-db:connect",
            "Resource": "arn:aws:rds-db:*:ACCOUNT_ID:dbuser:*/*_ro"
        }
    ]
}
```

**Comment by andrewpatto** [comment]
I mention it because at this level you don't use secrets at all

**Comment by williamputraintan** [comment]
So I think one of the downside of having this RDS-IAM is that the token used for the authentication needs to be refreshed [every 15 minutes](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.html), in the case of EdgeDb I am not sure whether we could set up a refresh mechanism from the EdgeDb server itself as we usually pass in the postgres DSN at the environment variable. (I guess possible could have like a cron job and parameter store to make it work?)
